### ISSUE TITLE
[Ressource] Lightmask Pack 01

### ISSUE THREAD

**Issue by clorl** [Godot-Engine-Francophone/godot-engine-francophone.github.io#12]
Nom: Lightmask Pack 01
Description: Pack de Lightmask
Type: snippets
Version de godot: 3.0+
[Lightmask_Pack01.zip](https://github.com/Godot-Engine-Francophone/godot-engine-francophone.github.io/files/4174605/Lightmask_Pack01.zip)

**Comment by xsellier** [comment]
Le top ce serait que ce pack de texture soit envoyé sur [opengameart](https://opengameart.org/content/you-must-be-logged-in-to-submit-art), comme ça nous pourrions le référer plus facilement

**Comment by xsellier** [comment]
Merci a Coldragon pour avoir créé un repository github.
La ressource est maintenant sur le site:
https://github.com/Godot-Engine-Francophone/godot-engine-francophone.github.io/commit/cc0502e031d73623b07affcd4c59ffca8f012dcb
