### ISSUE TITLE
[Ressource] ZIK MACHINE

### ISSUE THREAD

**Issue by supermoaaa** [Godot-Engine-Francophone/godot-engine-francophone.github.io#19]
Nom: zik machine
Description: logiciel de création live orienter pad / drum machine
écrit en gdscript 
[https://github.com/supermoaaa/zik-machine
![zikMachine003](https://user-images.githubusercontent.com/5919160/94193766-0b459f00-feb1-11ea-999d-4e7ed88db947.png)
](url)

Type: 
- projets

Version de godot: 3.2,

**Comment by xsellier** [comment]
Merci pour la suggestion, le logiciel vient d'etre ajouté à la liste!

**Comment by supermoaaa** [comment]
j'ai vu merci
