### ISSUE TITLE
[Showcase] Birdy World

### ISSUE THREAD

**Issue by bitsycore** [Godot-Engine-Francophone/godot-engine-francophone.github.io#20]
Jeu: Birdy World
Description: Un flappy bird like horizontal avec different skins a collecter et de nombreux mondes a explorer
Studio: Coldragon
Site web: 
    - https://play.google.com/store/apps/details?id=com.coldragon.birdyworld
    - https://www.amazon.com/Coldragon-Birdy-World/dp/B082FSDXB5
Asset: ![hello](https://user-images.githubusercontent.com/471393/98572770-4b70ad80-22b6-11eb-8f6f-042e57c5b5ab.gif)
Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour la proposition.
Pour le moment nous ne listons que les jeux disponibles en Français. Cela peut éventuellement changer, on en discute en interne.

**Comment by xsellier** [comment]
Avec un  peu de retard, le jeu est maintenant présent dans le showcase du site.
