### ISSUE TITLE
[Showcase] Fiscal Kombat European Edition

### ISSUE THREAD

**Issue by jmb462** [Godot-Engine-Francophone/godot-engine-francophone.github.io#21]
Jeu: Fiscal Kombat European Edition

Description: 

« Rendez l'argent ! »
Incarnez Manon Aubry en mission contre la fraude fiscale en Europe.
Secouez-les tous pour récolter l'argent et participer à la cagnotte commune contre l'évasion fiscale et pour la planification écologique.

Studio: Discord Insoumis

Site web: Application android disponible sur le PlayStore
https://play.google.com/store/apps/details?id=com.discord.insoumis

Asset: ![fk](https://user-images.githubusercontent.com/3649998/98571535-e7011e80-22b4-11eb-9908-01c96c06ee2a.png)

Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour l'ajout!
Ça devrait etre en ligne d'ici une petite heure

**Comment by jmb462** [comment]
Cool merci 😄
