### ISSUE TITLE
2D wind shader

### ISSUE THREAD

**Issue by jordanlis** [Godot-Engine-Francophone/godot-engine-francophone.github.io#25]
Nom: 2D wind shader
Description: Shader qui déplace les assets au gré du vent
Type: shaders
Version de godot: 2.1, 3.0, 3.1, 3.2, 4.0, master

// original wind shader from https://github.com/Maujoe/godot-simple-wind-shader-2d/tree/master/assets/maujoe.simple_wind_shader_2d
// original script modified by HungryProton so that the assets are moving differently
//
// speed - The speed of the wind movement.
// minStrength - The minimal strength of the wind movement.
// maxStrength - The maximal strength of the wind movement.
// strengthScale - Scalefactor for the wind strength.
// interval - The time between minimal and maximal strength changes.
// detail - The detail (number of waves) of the wind movement.
// distortion - The strength of geometry distortion.
// heightOffset - The height where the wind begins to move. By default 0.0.
 
shader_type canvas_item;
render_mode blend_mix;
 
// Wind settings.
uniform float speed = 1.0;
uniform float minStrength : hint_range(0.0, 1.0);
uniform float maxStrength : hint_range(0.0, 1.0);
uniform float strengthScale = 100.0;
uniform float interval = 3.5;
uniform float detail = 1.0;
uniform float distortion : hint_range(0.0, 1.0);
uniform float heightOffset = 0.0;
 
float getWind(vec2 vertex, vec2 uv, float time){
    float diff = pow(maxStrength - minStrength, 2.0);
    float strength = clamp(minStrength + diff + sin(time / interval) * diff, minStrength, maxStrength) * strengthScale;
    float wind = (sin(time) + cos(time * detail)) * strength * max(0.0, (1.0-uv.y) - heightOffset);
    
    return wind;
    }
 
void vertex() {
    vec4 pos = WORLD_MATRIX * vec4(0.0, 0.0, 0.0, 1.0);
    float time = TIME * speed + pos.x * pos.y;
    VERTEX.x += getWind(VERTEX.xy, UV, time);
}

![tree_wind](https://user-images.githubusercontent.com/68544949/103901733-d07f1400-50f9-11eb-8293-a55e2fd6c556.gif)

**Comment by xsellier** [comment]
Le site permet de faire des références vers des repository github. Nous ne nous occupons pas de maintenir des repository. On est une sorte de portail qui regroupe les projets/shaders/outils.
Ce qu'il faudrait faire c'est créer et maintenir ce shader, et ensuite rajouter la référence vers ce shader (qui peut etre un simple gist).

**Comment by jordanlis** [comment]
Et voilà ;p 
https://gist.github.com/jordanlis/7d21abf8857a465ac48126a8425f7f7a

**Comment by xsellier** [comment]
En cours de publication, cela devrait apparaitre dans quelques minutes.
