### ISSUE TITLE
[Ressource] Color replacement shader

### ISSUE THREAD

**Issue by deakcor** [Godot-Engine-Francophone/godot-engine-francophone.github.io#26]
Nom: Color replacement shader
Description: Un shader permettant de remplacer une couleur par une autre.
Type: Shaders
Version de godot: 3.x (fonctionne surement pour 2.x et 4.x)
OpenGL : GLES2, GLES3

Sans
![img1](https://user-images.githubusercontent.com/40196601/104005521-8c494d80-51a5-11eb-905f-2458703f4c22.png)

Avec
![img2](https://user-images.githubusercontent.com/40196601/104005525-8e131100-51a5-11eb-86ba-bb237aab4fef.png)

```
shader_type canvas_item;

uniform vec4 remove_color: hint_color;

uniform vec4 replace_color: hint_color;



void fragment(){
	vec4 col = texture(TEXTURE, UV);
	if (col.rgb == remove_color.rgb){
		col = replace_color;
	}
	COLOR = col;
}
```

(Utilisez le dans un viewport container pour l'appliquer sur plusieurs objets d'un même viewport)

https://gist.github.com/deakcor/e2c96a404550b7f022281780dd6342ce

**Comment by xsellier** [comment]
Bonjour,

Merci pour le shader cependant le site permet de faire des références vers des repository github. Nous ne nous occupons pas de maintenir des repository. On est une sorte de portail qui regroupe les projets/shaders/outils.
Ce qu'il faudrait faire c'est créer et maintenir ce shader, et ensuite rajouter la référence vers ce shader (qui peut etre un repository github complet ou alors un simple gist).

**Comment by deakcor** [comment]
J'ai ajouté un lien gist : https://gist.github.com/deakcor/e2c96a404550b7f022281780dd6342ce

**Comment by xsellier** [comment]
Super merci, c'est ajouté. Cela devrait apparaitre en ligne d'ici 5 a 10 minutes
