### ISSUE TITLE
[Ressource] Cropping shader

### ISSUE THREAD

**Issue by deakcor** [Godot-Engine-Francophone/godot-engine-francophone.github.io#27]
Nom: Cropping shader
Description: Permet de rogner une image. Il faut mettre les valeurs de 0 à 1 mais il peut être facilement adapté pour rentrer la valeur en pixel en multipliant par le pixel size (gles3 uniquement, sinon il faut faire un paramètre en plus pour indiquer la taille de l'image).
Type: Shaders
Version de godot: 3.x
OpenGL: 2, 3

![Image1](https://user-images.githubusercontent.com/40196601/104006899-6de45180-51a7-11eb-9f4f-3ee13c5ea66f.png)

```
shader_type canvas_item;

uniform float crop_left:hint_range(0.0,1.0,0.01) = 0.0;
uniform float crop_right:hint_range(0.0,1.0,0.01) = 0.5;
uniform float crop_top:hint_range(0.0,1.0,0.01) = 0.0;
uniform float crop_bottom:hint_range(0.0,1.0,0.01) = 0.0;

void fragment(){
	vec4 color = texture(TEXTURE,UV);
	if (UV.x<=crop_left || UV.x>=1.0-crop_right || UV.y>=1.0-crop_bottom || UV.y<=crop_top){
		color.a = 0.0;
	}
	COLOR = color;
}
```

https://gist.github.com/deakcor/394db005c6bd1ef3153cf6b709ebd252

**Comment by xsellier** [comment]
Bonjour,

Merci pour le shader cependant le site permet de faire des références vers des repository github. Nous ne nous occupons pas de maintenir des repository. On est une sorte de portail qui regroupe les projets/shaders/outils.
Ce qu'il faudrait faire c'est créer et maintenir ce shader, et ensuite rajouter la référence vers ce shader (qui peut etre un repository github complet ou alors un simple gist).

**Comment by deakcor** [comment]
Lien gist ajouté : https://gist.github.com/deakcor/394db005c6bd1ef3153cf6b709ebd252

**Comment by xsellier** [comment]
Super merci, c'est ajouté. Cela devrait apparaitre en ligne d'ici 5 a 10 minutes
