### ISSUE TITLE
[Ressource] Firebase cloud firestore parser

### ISSUE THREAD

**Issue by deakcor** [Godot-Engine-Francophone/godot-engine-francophone.github.io#29]
Nom: Firebase cloud firestore parser
Description: Parse des données récupérées du cloud firestore de Firebase
Type: snippets
Version de godot: 3.x

https://gist.github.com/deakcor/5da044e5ca979dc58b176ab40df34d4a

**Comment by xsellier** [comment]
Ce serait bien que le gist donne un lien vers le connecteur firebase qui est utilisé. Parce qu'en l'état le snippet ne se suffit pas a lui même.

**Comment by deakcor** [comment]
J'ai rajouté un exemple utilisable

**Comment by xsellier** [comment]
Merci pour le partage, c'est ajouté, ça devrait être en ligne d'ici quelques minutes.
