### ISSUE TITLE
[Showcase] En attendant 9h15

### ISSUE THREAD

**Issue by polygoniaC-album** [Godot-Engine-Francophone/godot-engine-francophone.github.io#34]
Jeu: En attendant 9h15
Description: Il est bientôt 9h15, mais pas tout à fait. Enfin, il serait bientôt 9h15 si le temps ne passait pas si lentement et, surtout, si cette horloge n'était pas cassée.

Un point-and-click à jouer avant d'aller dormir. 
Studio: Obeqaen
Site web: https://obeqaen.itch.io/en-attendant-9h15
Asset: 
Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour la contribution.
Le jeu vient d'etre ajouté il sera en ligne d'ici quelques minutes

**Comment by polygoniaC-album** [comment]
Merci beaucoup !


De : Xavier Sellier ***@***.***>
À : Godot-Engine-Francophone/godot-engine-francophone.github.io ***@***.***>
Sujet : Re: [Godot-Engine-Francophone/godot-engine-francophone.github.io] [Showcase] En attendant 9h15 (#34)
Date : 20/09/2021 09:11:12 Europe/Paris
Copie à : polygoniaC-album ***@***.***>;
   Author ***@***.***>


Merci pour la contribution.
Le jeu vient d'etre ajouté il sera en ligne d'ici quelques minutes

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
