### ISSUE TITLE
[Showcase] Little adventure

### ISSUE THREAD

**Issue by imikado** [Godot-Engine-Francophone/godot-engine-francophone.github.io#35]
Jeu: Little adventure
Description: Jeu d'aventure ou vous aider Gordon a trouver les pièces pour réparer le puit du village.
Studio: indépendant (dupot.org)
Site web: https://play.google.com/store/apps/details?id=dupot.org.mika.littleadventure
Asset: (optionnel) lien d'une démo en HTML5: https://www.dupot.org/demo/LittleAdventure/
Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour la contribution.
Le jeu vient d'etre ajouté il sera en ligne d'ici quelques minutes
