### ISSUE TITLE
[Showcase] Broken Lens

### ISSUE THREAD

**Issue by HephepTeam** [Godot-Engine-Francophone/godot-engine-francophone.github.io#44]
Jeu: Broken Lens
Description: Broken Lens est un jeu relaxant qui renouvelle l'expérience du jeu des 7 différences : repérez les différences entre deux scènes et suivez l'histoire du petit robot ayant un problème de vue. Collectionnez les pages du livres, découvrez des secrets, jouez à votre rythme!
Studio: Team RUN
Site web: https://store.steampowered.com/app/2184770/Broken_Lens/
Asset: https://imgur.com/0LjyrWL
Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour le partage.
Le jeu vient d'être ajouté au showcase, il devrait apparaitre d'ici une dizaine de minutes sur le site.
