### ISSUE TITLE
[Showcase] Dice'n Goblins

### ISSUE THREAD

**Issue by Elesh-Norn** [Godot-Engine-Francophone/godot-engine-francophone.github.io#45]
Jeu: Dice'n Goblins
Description: Explore un mystérieux donjon dans ce Dungeon Crawler RPG. Utilise tes dés et sois malin dans le combat tour par tour. Seul l'utilisation astucieuse de tes compétences te permettra de faire des combos et être meilleur que la chance. Loot, Achètes et Améliores ton set de dés pour combattre les monstres fous et les humains!
Studio: Tsukumogami Software
Site web: [Lien vers le jeu (Steam, google play store...)](https://store.steampowered.com/app/2945950/Dice_n_Goblins/)
Asset: 
![TrailerArt](https://github.com/Godot-Engine-Francophone/godot-engine-francophone.github.io/assets/29737733/b660db43-3a50-47f3-9df5-3f3836bace02)

![CombatComboCrop-1](https://github.com/Godot-Engine-Francophone/godot-engine-francophone.github.io/assets/29737733/e5ccef35-6397-42ba-9bc1-757fc36d2619)
![ExploreBigCropped](https://github.com/Godot-Engine-Francophone/godot-engine-francophone.github.io/assets/29737733/9b2cad37-f1a3-429a-8dc2-1647b3ca7c8f)

Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour le partage.
Le jeu vient d'être ajouté au showcase, il devrait apparaitre d'ici une dizaine de minutes sur le site.
