### ISSUE TITLE
[Showcase] Xion Leak

### ISSUE THREAD

**Issue by MrBSmith** [Godot-Engine-Francophone/godot-engine-francophone.github.io#46]
Jeu: Xion Leak
Description: Xion Leak est un jeu de plateforme 2D en coop à deux joueurs porté sur la vitesse.
Il est question de progresser à deux dans des niveaux et d’y obtenir les chronos les plus bas possible pour décrocher les trophées bronze/argent/or.
Le jeu se déroule dans un univers au pixel art fin et coloré, dans une ambiance loufoque et rythmée par une bande son survitaminée.
Vous incarnez deux robots aux capacités différentes et devez collaborer pour vous enfuir d'une usine où tout vous est hostile !
Pour ne rien arranger, le Xion, gaz ultra corrosif, vous poursuit et détruit tout sur son passage !
Studio: Gentle Beasts Studio
Site web: https://store.steampowered.com/app/1948490/Xion_Leak/
Asset: https://drive.google.com/file/d/1nvE7Mxl0LE8zfjcSWASTab_QG3VzqJtw/view?usp=sharing
Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour le jeu.
Il vient d'etre ajouté aux showcase! Bonne chance pour la sortie!
