### ISSUE TITLE
[Showcase] Fair and Square

### ISSUE THREAD

**Issue by SimonPiCarter** [Godot-Engine-Francophone/godot-engine-francophone.github.io#47]
Jeu: Fair and Square
Description: Fair and Square est un jeu de stratégie en temps réel développé avec Godot dans lequel il vous faudra défendre votre base contre des vagues d'ennemis de plus en plus puissantes. Heureusement que vous pouvez débloquer des bonus au fur et à mesure que la partie évolue afin de surmonter ce défi. Il sera nécessaire de s'étendre pour récolter des ressources et garder votre base en vie! 
Studio: Octopus Engine
Site web: [Lien vers le jeu (Steam, google play store...)](https://store.steampowered.com/app/2546350/Fair_and_Square)
Asset: (optionnel) https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2546350/extras/rts_steam-ezgif.com-optimize.gif?t=1718901278
Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci pour l'ajout, ce sera disponible dans l'apres midi!
