### ISSUE TITLE
Aseprite : Tutoriels et Guides complets

### ISSUE THREAD

**Issue by BiosArt43** [Godot-Engine-Francophone/godot-engine-francophone.github.io#48]
### Aseprite : Tutoriels et Guides complets
Plongez dans l'univers coloré de [Pix Au Carré](https://pixaucarre.fr), votre ressource francophone ultime pour des tutoriels complets sur le **Pixel Art**. Que vous soyez débutant ou utilisateur avancé, nos guides inspirants et détaillés vous apprendront à maîtriser des outils comme Aseprite. Découvrez des exemples captivants en images et en vidéos pour perfectionner vos compétences en Pixel Art, en Animation et dans la création d'assets pour jeux vidéo.

**Comment by xsellier** [comment]
Merci pour l'ajout, ce sera disponible dans l'apres midi!

**Comment by BiosArt43** [comment]
![Aseprite Tutoriels](https://github.com/user-attachments/assets/b4f66442-2247-44bd-9325-90c201003ead)
Je me permets de te passer l'image que je voudrais bien en Aperçu

**Comment by BiosArt43** [comment]
Salut Bino, je me permets de revenir vers toi, j'ai vu que tu n'avais pas encore mis à jour le thumbnail, et ça tombe bien, j'ai apporté qq modif. Donc merci à toi de prendre en compte cette nouvelle img en guise de présentation. Bonne journée :)

![Accueil AsepriteV2(1)](https://github.com/user-attachments/assets/7c2b47d7-4f64-4dac-95f0-a6141a23fde6)

**Comment by xsellier** [comment]
Merci pour la mise a jour. Je viens de faire les changements
