### ISSUE TITLE
[Ressource] Installer et Tester votre jeu Godot sur iOS sans compte payant Apple

### ISSUE THREAD

**Issue by bitsycore** [Godot-Engine-Francophone/godot-engine-francophone.github.io#5]
Nom: Installer et Tester votre jeu Godot sur iOS sans compte payant Apple
Description: Lancer votre jeu Godot sur n'importe quel appareil iOS 8 ou plus pour le tester sans compte payant, parfait si vous developpez votre premier jeu pour iOS sans payer directement un compte Apple.
Type: snippets
Version de godot: 3.1, 3.2

https://gist.github.com/Coldragon/2b28bb8a5f4f469db764c7a44982ca43

**Comment by xsellier** [comment]
Super merci,
J'ajoute ça de ce pas!

**Comment by xsellier** [comment]
Ajouté aux snippets:
https://www.godot-francophone.org/resources/snippets/

Merci pour ta contribution
