### ISSUE TITLE
[Showcase] Fallacy Quiz

### ISSUE THREAD

**Issue by timkrief** [Godot-Engine-Francophone/godot-engine-francophone.github.io#50]
Jeu: Fallacy Quiz

Description: Fallacy Quiz est un jeu qui teste votre capacité à identifier les raisonnements trompeurs ou incorrects, aussi connus sous le nom de raisonnements fallacieux. Les joueurs peuvent améliorer leur esprit critique et reconnaître plus facilement les arguments insidieux dans leur vie quotidienne. Devant divers énoncés, ils devront déterminer s’ils sont valides ou fallacieux ou même, dans le mode expert, identifier le type de sophisme spécifique employé.

Studio: Tim Krief

Site web: https://fallacyquiz.com

Asset: (optionnel) Celui là m'a l'air pas mal:
![gif](https://projects.timkrief.com/wp-content/uploads/2024/04/NcoxJW.gif)

Mais d'autres sont dispo dans le [presskit](https://projects.timkrief.com/presskit/fallacy-quiz/?lang=fr)

Contenu pour adultes: Non

**Comment by xsellier** [comment]
Merci! Ça vient d'être ajouté!
Très beau jeu en passant. Il devrait etre visible sur le site dans la journée

**Comment by timkrief** [comment]
Super!
