### ISSUE TITLE
[Evenement] Rencontres Godot Lyon

### ISSUE THREAD

**Issue by Daydreel** [Godot-Engine-Francophone/godot-engine-francophone.github.io#52]
Nom: Rencontres Godot Lyon
Date d'inscription : ouvert
Date de l'évènement: Lundi 9 septembre
Lieu: Loop's au 40 Avenue Henri Barbusse 69100 Villeurbanne
Description: Description de l'évènement. Qui l'organise, pourquoi, et ce qu'on y fait.

Bonjour amis·es devs indé ! 🙂

Rejoignez-nous pour une rencontre enrichissante entre créateurs·rices Godot. Cinq volontaires partageront leurs expériences dans une ambiance conviviale et collaborative.

La soirée est découpée en deux temps. La présentation des jeux de créateurs·rices puis un temps d’échanges et d’entraide. Chacun·e est invité·e à participer aux discussions autour des projets présentés.

Peu importe l'avancement de votre projet, que ce soit une idée, un concept ou une pré-production, toute personne est la bienvenue !
Cultivons un esprit d’entraide !

Accueil => 19:00 PM
Présentation => 20:00 PM
Échange et entraide => 21:00 PM

Retrouvez plus d’infos sur Eventbrite :
https://rencontregodot.eventbrite.fr/

Ou contacter @Daydreel pour vos questions

**Comment by xsellier** [comment]
Ajouté au site.
