### ISSUE TITLE
FranckushiMama RPG sur mobile (Gratuit)

### ISSUE THREAD

**Issue by kilouw** [Godot-Engine-Francophone/godot-engine-francophone.github.io#54]
**FranckushiMama** 

FranckushiMama est un RPG au tour par tour sur mobile.

**Langue disponible :** Français et Anglais
**Durée du jeu** : environ 30 à 40 heures de jeu, 3 niveaux de difficulté

L'histoire se déroule dans un univers médiéval et fantastique. Au royaume de FranckushiMama, le pouvoir en place tente de se maintenir par la répression et la propagande et les conditions de vie des citoyens deviennent de plus en plus difficile.
Coïncidence, une invasion de créatures mystérieuses survient alors que des révoltes se font de plus en plus nombreuses.
De son côté, Wholian s'entraîne chaque jour dans le but d'être n°1 au lancer de fléchettes mais cette invasion va influencer son destin.
Face à cette situation, 8 héros sont rassemblés pour protéger FranckushiMama.

**Le mot du développeur :**

J'ai baigné dans l'univers des RPG (Jeu de Rôle) depuis très jeune et en grandissant je me suis dit que c'était un support comme les films et la musique, pour partager des choses et traiter plein de thématiques de société.

**Trailer :** [https://youtu.be/oG9A_Ldou9w?feature=shared](https://youtu.be/oG9A_Ldou9w?feature=shared)

Lien PlayStore : [https://play.google.com/store/apps/details?id=org.godotengine.franckushimama](https://play.google.com/store/apps/details?id=org.godotengine.franckushimama)

Lien App Store : [https://apps.apple.com/fr/app/franckushimama/id6504882306](https://apps.apple.com/fr/app/franckushimama/id6504882306)

Contenu pour adultes: Non

![Screena](https://github.com/user-attachments/assets/b5bb198b-3b9a-4370-a29e-9e26fe9f06d9)
![screendial2](https://github.com/user-attachments/assets/a0e08d04-8e8a-4a6d-8e6c-02ec4c512851)

![screenfight2](https://github.com/user-attachments/assets/7fc86512-0f09-4410-b7f1-96647364dd2a)
![screenmap1](https://github.com/user-attachments/assets/2db85c58-e768-4b3a-ae0e-45e7d627f813)
![screenmap2](https://github.com/user-attachments/assets/41801642-ec1d-4128-b4f6-0c1b15b27b96)
![screenmap3](https://github.com/user-attachments/assets/9630197b-699d-4e55-a095-159447f28820)

**Comment by xsellier** [comment]
Bonjour,

Je viens de regarder le ticket. Il y a quelques problemes.
Le premier c'est la description, Ce doit etre une seule phrase simple.
Ensuite il manque le nom du Studio.
Et puis, on ne peut mettre qu'un seul lien, donc il faut choisir entre iOS et Android.
Et en dernier il faut un gif, ça rend mieux sur le site.

**Comment by xsellier** [comment]
Jeu ajouté. Merci
