### ISSUE TITLE
[Ressource] Crypth of the GodoDancers

### ISSUE THREAD

**Issue by LeProfesseurStagiaire** [Godot-Engine-Francophone/godot-engine-francophone.github.io#7]
Nom: Crypth of the GodoDancers
Description: une copie des mécaniques de jeu de crypth of the necrodancer
Type: projets
Version de godot: 3.1

lien du git : https://github.com/LeProfesseurStagiaire/crypt-of-the-Godot-Dancer

**Comment by xsellier** [comment]
Salut @LeProfesseurStagiaire 

Merci pour le partage. Pourrais-tu ajouter un fichier README.md avec une description du projet (directement dans ton repository github).
- Nom du projet
- Description rapide du jeu (genre de jeu, theme)
- Version de godot engine avec laquelle le jeu a été testé

En bonus une capture d'écran du jeu serait top

**Comment by xsellier** [comment]
Ajouté au site.
Merci pour le partage
